CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211222175722_MigrationInicial') THEN
    CREATE TABLE "Cliente" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" VARCHAR(80) NOT NULL,
        "Telefone" CHAR(11) NULL,
        "CEP" CHAR(8) NOT NULL,
        "Estado" CHAR(2) NOT NULL,
        "Cidade" character varying(60) NOT NULL,
        CONSTRAINT "PK_Cliente" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211222175722_MigrationInicial') THEN
    CREATE TABLE "Produto" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CodigoBarras" VARCHAR(14) NOT NULL,
        "Descricao" VARCHAR(60) NULL,
        valor numeric NOT NULL,
        "TipoProduto" text NOT NULL,
        "Ativo" boolean NOT NULL,
        CONSTRAINT "PK_Produto" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211222175722_MigrationInicial') THEN
    CREATE TABLE "Pedido" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ClienteID" integer NOT NULL,
        "IniciadoEm" timestamp without time zone NOT NULL,
        "FinalizadoEm" timestamp without time zone NOT NULL,
        "TipoFrete" integer NOT NULL,
        "StatusPedido" text NOT NULL,
        "Observacao" VARCHAR(512) NULL,
        CONSTRAINT "PK_Pedido" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Pedido_Cliente_ClienteID" FOREIGN KEY ("ClienteID") REFERENCES "Cliente" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211222175722_MigrationInicial') THEN
    CREATE TABLE "PedidoItem" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PedidoId" integer NOT NULL,
        "ProdutoId" integer NOT NULL,
        "Quantidade" integer NOT NULL DEFAULT 1,
        "Valor" numeric NOT NULL,
        "Desconto" numeric NOT NULL,
        "PedidoItemId" integer NULL,
        CONSTRAINT "PK_PedidoItem" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PedidoItem_Pedido_PedidoId" FOREIGN KEY ("PedidoId") REFERENCES "Pedido" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PedidoItem_PedidoItem_PedidoItemId" FOREIGN KEY ("PedidoItemId") REFERENCES "PedidoItem" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_PedidoItem_Produto_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES "Produto" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211222175722_MigrationInicial') THEN
    CREATE INDEX idx_cliente_telefone ON "Cliente" ("Telefone");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211222175722_MigrationInicial') THEN
    CREATE INDEX "IX_Pedido_ClienteID" ON "Pedido" ("ClienteID");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211222175722_MigrationInicial') THEN
    CREATE INDEX "IX_PedidoItem_PedidoId" ON "PedidoItem" ("PedidoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211222175722_MigrationInicial') THEN
    CREATE INDEX "IX_PedidoItem_PedidoItemId" ON "PedidoItem" ("PedidoItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211222175722_MigrationInicial') THEN
    CREATE INDEX "IX_PedidoItem_ProdutoId" ON "PedidoItem" ("ProdutoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211222175722_MigrationInicial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20211222175722_MigrationInicial', '5.0.10');
    END IF;
END $EF$;
COMMIT;

